name: flutter_chat_ui
description: A lightweight, customizable chat UI kit for Flutter.
version: 0.1.0
environment:
  sdk: ^3.6.0
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
